name: Node tests

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  versions:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    outputs:
      nodeVersion: ${{ steps.versions.outputs.nodeVersion }}
      npmVersion: ${{ steps.versions.outputs.npmVersion }}

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@8205673bab74a63eb9b8093402fd9e0e018663a1
        id: versions
        with:
          fallbackNode: '^16'
          fallbackNpm: '^7'

  test:
    runs-on: ubuntu-latest
    needs: versions

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up node ${{ needs.versions.outputs.nodeVersion }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: ${{ needs.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ needs.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ needs.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Test and process coverage
        run: npm run test:coverage
  
      - name: Collect coverage
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          files: ./coverage/lcov.info

  jsunit:
    runs-on: ubuntu-latest
    needs: versions

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up node ${{ needs.versions.outputs.nodeVersion }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: ${{ needs.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ needs.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ needs.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:jsunit

  handlebars:
    runs-on: ubuntu-latest
    needs: versions

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up node ${{ needs.versions.outputs.nodeVersion }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: ${{ needs.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ needs.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ needs.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Run compile
        run: ./build/compile-handlebars-templates.sh
