name: PHPUnit oci

on: pull_request

permissions:
  contents: read

concurrency:
  group: phpunit-oci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-oci:
    runs-on: ubuntu-20.04

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']

    services:
      oracle:
        image: ghcr.io/gvenzl/oracle-xe:11

        # Provide passwords and other environment variables to container
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: autotest
          APP_USER_PASSWORD: owncloud

        # Forward Oracle port
        ports:
          - 1521:1521/tcp

        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout server
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: true

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d #v2.25.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, curl, dom, fileinfo, gd, imagick, intl, json, mbstring, oci8, openssl, pcntl, pdo_sqlite, posix, sqlite, xml, zip
          tools: phpunit:9
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=oci --database-name=XE --database-host=127.0.0.1 --database-port=1521 --database-user=autotest --database-pass=owncloud --admin-user admin --admin-pass admin
          php -f index.php

      - name: PHPUnit
        working-directory: tests
        run: phpunit --configuration phpunit-autotest.xml --group DB,SLOWDB

      - name: Run repair steps
        run: |
          ./occ maintenance:repair --include-expensive

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: phpunit-oci

    if: always()

    name: phpunit-oci-summary

    steps:
      - name: Summary status
        run: if ${{ needs.phpunit-oci.result != 'success' }}; then exit 1; fi
